server:
  port: 8006

spring:
  application:
    name: cloud-consulconsumer-order
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}