server:
  port: 9527

spring:
  application:
    name: cloud-gateway #服务名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2020-08-25T21:28:52.171+08:00[Asia/Shanghai]
#            - Cookie=username,zhengcj
    
#        - id: payment_routh2
##          uri: http://localhost:8001
#          uri: lb://CLOUD-PAYMENT-SERVICE
#          predicates:
#            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            
#        - id: payment_routh3
#          uri: http://news.baidu.com
#          predicates:
#            - Path=/guonei   #断言,路径相匹配的进行路由
#            
#        - id: payment_routh3
#          uri: http://news.baidu.com
#          predicates:
#            - Path=/guoji   #断言,路径相匹配的进行路由
  

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #不集群 指向自己
      #defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # 入驻地址 集